### ISSUE TITLE
[1.12.2] No Steel anvil UI

### ISSUE THREAD

**Issue by GWSheridan** [BetterWithMods/BetterWithMods#734]
Unable to access UI of soulforged steel anvil

Versions
BWM: 1.12.2-2.0.24
Forge: 14.23.1.2589
MC: 1.12.2

**Comment by primetoxinz** [comment]
This is apparently due to OpenBlocks, I have no idea why and they must be hacking something pretty badly to cause it

**Comment by GWSheridan** [comment]
weird will report it on there github as i am using that mod as well

**Comment by boq** [comment]
Meh, wouldn't call one-line mistake "hacking"...

Due to error, for one of our recipes (marked as dynamic) `width*height != getIngredients().size()`. And then [this happens](https://github.com/BetterWithMods/BetterWithMods/blob/1.12/src/main/java/betterwithmods/common/registry/anvil/VanillaShapedAnvilRecipe.java#L33). 

I will fix it on my side, but your code could be more robust (or at least print failing recipe class).
