### ISSUE TITLE
Sawmill does not match all logs properly

### ISSUE THREAD

**Issue by justinrusso** [BetterWithMods/BetterWithMods#919]
The sawmill matching is inconsistent. Some logs it matches perfectly fine when places on the floor in front of the saw, while others require it to be clicked directly onto it (with the wood part facing, rather than bark)

Reference https://github.com/DarkPacks/SevTech-Ages/issues/2369

**Comment by primetoxinz** [comment]
Ok, that is the issue. 
Turns out I forgot to put it on the CT docs.
Due to how logs work, being that they have many states that drop the same item you have to use a custom recipe called BlockDrop that can be done like so:
Unfortunately, it wasn't thought out (*cough* bord *cough*) and you have to set the input twice.
```
mods.betterwithmods.Saw
.builder()
.buildRecipe(IIngredient inputBlock, IItemStack[] outputs)
.setInputBlockDrop(IItemStack input)
.build();
```

**Comment by justinrusso** [comment]
> Unfortunately, it wasn't thought out (cough bord cough) and you have to set the input twice.

This is quite clear considering the input can be an IIngredient, yet needs to be an IItemStack for the block drop. It is also confusing how some work, yet others do not, and why face is taken into consideration when matching the blocks.

**Comment by primetoxinz** [comment]
It is not "face" that is taken into consideration, it is the fact that these are __BlockState__ based recipes, not just __block__ based. Meaning you can potentially have a different recipe for each direction of the log (even if that doesn't make much sense in specificially).
You are correct that the input should be IIngredient, I will try to get that into Modtweaker when I get the chance...

**Comment by DaedalusGame** [comment]
>why face is taken into consideration when matching blocks
as you probably know there's no clear mapping from blockstate <-> itemstack. Different blockstates in world have different meta values and doing a wildcard match is sometimes not possible because the implementation of the block meta mapping can include several logs in one blockid. What block recipes should actually take is a displayed itemstack(array) for JEI and a blockpattern. Doing this would create horrible issues for packdevs, as blockstates and by extension blockpatterns cannot be easily created in CT (I've asked for this feature several times now but I keep getting deflected to using CoT's blockstate syntax). Also it's still a problem because of the aforementioned multiple logs in one block. Welcome to minecraft modding.
>yet needs to be an IItemStack for the block drop.
Probably some internal implementation specific of BlockDropIngredient that I didn't want to mess with. Changing anything CT integration related is a huge pain in the arse as it is, as to do anything I have to change it on BWM's side, build it on the jenkins, then add it on ModTweaker's side.

**Comment by justinrusso** [comment]
```
No such member in com.blamejared.compat.betterwithmods.base.blockrecipes.SawBuilder: setInputBlockDrop
```

Script:
```
import mods.betterwithmods.Saw;

for plank, logs in plankLogPairs {
	for log in logs {
		for logItem in log.items {
			Saw.builder()
				.buildRecipe(log, [plank * 6, <ore:dustWood>.firstItem * 2])
				.setInputBlockDrop(logItem as IItemStack)
				.build();
		}
	}
}
```
Where `plankLogPairs` is an `IIngredient[][IItemStack]`

**Comment by primetoxinz** [comment]
Right... that method was added in ModTweaker 4.0.12

**Comment by justinrusso** [comment]
Right, thanks.
